spring.application.name=servidor-central
server.port=8080
# URL de conexión (Apuntando a localhost y la base de datos 'postgres')
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de Hibernate / JPA
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Formato de logs (Opcional, ayuda a depurar errores criptográficos)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración para Format-Preserving Encryption (FPE)
app.crypto.fpe-key=2B7E151628AED2A6ABF7158809CF4F3C
app.crypto.fpe-tweak=RVNDT00tVFdFQUs=